export const apiRoutes = {
  get_layout: "layout",
  home_page: "pages/home",
  about_page: "pages/about",
  fare_flight_page: "pages/fare-flight",
  our_offers_page: "pages/our-offers",
  contact_page: "pages/contact",
  blogs_page: "pages/blogs",
  blog_detail: (id) => `pages/blogs/${id}`,
  services_page: "pages/services",
  tours_by_destination: (slug) => `pages/tours/${slug}`,
  tour_detail: (destSlug, tourSlug) => `pages/tours/${destSlug}/${tourSlug}`,
  umrah_page:     "pages/umrah",
  umrah_register: "pages/umrah-register",
  intl_tours_page:   "pages/intl-tours",
  visa_page:         "pages/visa-page",
  visa_form_data:    "pages/visa-form-data",
  visa_apply:        "pages/visa-apply",
  legal_doc:         (slug) => `pages/legal/${slug}`,
  online_payment:    "pages/online-payment",
  car_reservation_page: "pages/car-reservation",
  car_reservation_book: "pages/car-reservation/book",
};