"use client";
import Header from "@/layouts/Header/Header";
import Footer from "@/layouts/Footer/Footer";
import AosAnimation from "@/components/shared/AosComponent/AosComponent";
import { Geist, Geist_Mono } from "next/font/google";
import { usePathname } from "next/navigation";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Head from "next/head";
import { UmrahProvider } from "@/context/UmrahContext";
import DefaultLayout from "../components/DefaultLayout";
import { useDispatch, useSelector } from "react-redux";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Uno Travel",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/images/Group47503-ezgif.com-gif-maker.svg",
//   },
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  // List of paths where Header/Footer should be hidden
  const hideLayout = ["/sign-in"].some((path) => pathname.startsWith(path));
 if (typeof window === 'undefined') {
    return null;
  }

  return (
    <html lang="en">
      <Head>
        <title>Uno Travel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/Group47503-ezgif.com-gif-maker.svg" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ overflowY: "auto", minHeight: "100vh" }}
      >
        <DefaultLayout>
          <UmrahProvider>
            {!hideLayout && <Header />}
            <main>{children}</main>
            {!hideLayout && <Footer />}
          </UmrahProvider>
            <AosAnimation />
        </DefaultLayout>
      </body>
    </html>
  );
}
